package com.ikkong.dg.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade. 2017-09-24 12:44:38
 */
@Table(name = "dg_work_order")
@BindID(name = "id")
@SuppressWarnings("serial")
public class WorkOrder extends BaseModel {
	
	private Long id;
	private Integer order_date; // 订单周期，以天为单位
	private Integer status; // 项目状态，0待审，1招标中，2已招标，3项目进行中， 4完成，5终止
	private Integer version; // 版本记录号
	private Integer worktype_id; // 工种类型id
	private Long accept_user_id; // 如果状态为已接单，该项填入接单人id
	private Long create_id; // 创建订单的电工用户id
	private String mark; // 项目描述，长度不能大于500
	private Double money; // 项目金额
	private Double total_money;//总金额
	private Long order_id; // 订单id
	private Double subsidy; // 补贴金额，具体金额数，按天计算
	private String subsidy_mark; // 补贴说明
	private Date publish_time;//发布中时间
	private Date biding_time;//招标中时间
	private Date overbid_time;//已招标时间
	private Date proceed_time;//进行时间 
	private Date revocation_time;//撤销时间
	private Date accpet_time; // 订单接收时间
	private Date create_time; // 订单创建时间
	private Date finish_time; // 完成时间
	private Integer reject_times;//拒绝次数

	@AutoID
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getOrder_date() {
		return order_date;
	}

	public void setOrder_date(Integer order_date) {
		this.order_date = order_date;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getWorktype_id() {
		return worktype_id;
	}

	public void setWorktype_id(Integer worktype_id) {
		this.worktype_id = worktype_id;
	}

	public Long getCreate_id() {
		return create_id;
	}

	public void setCreate_id(Long create_id) {
		this.create_id = create_id;
	}

	public String getMark() {
		return mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}

	public Long getOrder_id() {
		return order_id;
	}

	public void setOrder_id(Long order_id) {
		this.order_id = order_id;
	}

	public String getSubsidy_mark() {
		return subsidy_mark;
	}

	public void setSubsidy_mark(String subsidy_mark) {
		this.subsidy_mark = subsidy_mark;
	}

	public Date getAccpet_time() {
		return accpet_time;
	}

	public void setAccpet_time(Date accpet_time) {
		this.accpet_time = accpet_time;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getFinish_time() {
		return finish_time;
	}

	public void setFinish_time(Date finish_time) {
		this.finish_time = finish_time;
	}

	public Double getMoney() {
		return money;
	}

	public void setMoney(Double money) {
		this.money = money;
	}
	
	public Double getTotal_money() {
		return total_money;
	}

	public void setTotal_money(Double total_money) {
		this.total_money = total_money;
	}

	public Double getSubsidy() {
		return subsidy;
	}

	public void setSubsidy(Double subsidy) {
		this.subsidy = subsidy;
	}

	public Long getAccept_user_id() {
		return accept_user_id;
	}

	public void setAccept_user_id(Long accept_user_id) {
		this.accept_user_id = accept_user_id;
	}

	public Integer getReject_times() {
		return reject_times;
	}

	public void setReject_times(Integer reject_times) {
		this.reject_times = reject_times;
	}

	public Date getPublish_time() {
		return publish_time;
	}

	public void setPublish_time(Date publish_time) {
		this.publish_time = publish_time;
	}

	public Date getBiding_time() {
		return biding_time;
	}

	public void setBiding_time(Date biding_time) {
		this.biding_time = biding_time;
	}

	public Date getOverbid_time() {
		return overbid_time;
	}

	public void setOverbid_time(Date overbid_time) {
		this.overbid_time = overbid_time;
	}

	public Date getProceed_time() {
		return proceed_time;
	}

	public void setProceed_time(Date proceed_time) {
		this.proceed_time = proceed_time;
	}

	public Date getRevocation_time() {
		return revocation_time;
	}

	public void setRevocation_time(Date revocation_time) {
		this.revocation_time = revocation_time;
	}

}
