package com.ikkong.dg.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
@Table(name = "dg_audit_files")
@BindID(name = "id")
@SuppressWarnings("serial")
public class AuditFiles extends BaseModel {
    	private Long id; //自增长ID
    	private Integer version;
    	private String file_name; //文件名
    	private String file_path; //文件路径
    	private String file_postfix; //文件后缀
    	private Long object_id; //所属对象id
    	private String object_type; //文件所属类别
    	private Date create_tm; //创建时间

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getFile_name() {
    		return file_name;
    	}

    	public void setFile_name(String file_name) {
    		this.file_name = file_name;
    	}

    	public String getFile_path() {
    		return file_path;
    	}

    	public void setFile_path(String file_path) {
    		this.file_path = file_path;
    	}

    	public String getFile_postfix() {
    		return file_postfix;
    	}

    	public void setFile_postfix(String file_postfix) {
    		this.file_postfix = file_postfix;
    	}

    	public Long getObject_id() {
    		return object_id;
    	}

    	public void setObject_id(Long object_id) {
    		this.object_id = object_id;
    	}

    	public String getObject_type() {
    		return object_type;
    	}

    	public void setObject_type(String object_type) {
    		this.object_type = object_type;
    	}

    	public Date getCreate_tm() {
    		return create_tm;
    	}

    	public void setCreate_tm(Date create_tm) {
    		this.create_tm = create_tm;
    	}

}
