package com.ikkong.dg.model;

import java.math.BigDecimal;
import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
@Table(name = "dg_business")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Business extends BaseModel {
    	private Long id;
    	private Integer type; //交易类型0无，1充值，2提现，3付款，4收款，5罚款，6奖励
    	private Integer version;
    	private Long dg_id; //电工用户ID
    	private String mark; //交易说明,150个字符之内

    	private BigDecimal money; //交易金额
    	private Date create_time; //创建时间

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getType() {
    		return type;
    	}

    	public void setType(Integer type) {
    		this.type = type;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public Long getDg_id() {
    		return dg_id;
    	}

    	public void setDg_id(Long dg_id) {
    		this.dg_id = dg_id;
    	}

    	public String getMark() {
    		return mark;
    	}

    	public void setMark(String mark) {
    		this.mark = mark;
    	}

    	public BigDecimal getMoney() {
    		return money;
    	}

    	public void setMoney(BigDecimal money) {
    		this.money = money;
    	}

    	public Date getCreate_time() {
    		return create_time;
    	}

    	public void setCreate_time(Date create_time) {
    		this.create_time = create_time;
    	}

}
