package com.ikkong.dg.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-11-30 17:38:22
 */
@Table(name = "dg_msg_template")
@BindID(name = "id")
@SuppressWarnings("serial")
public class DgMsgTemplate extends BaseModel {
    	private Integer id;
    	private Integer type; //消息类型
    	private Integer version;
    	private String code; //消息编码
    	private String content; //消息内容
    	private String name; //消息名
    	private String scence; //消息场景

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getType() {
    		return type;
    	}

    	public void setType(Integer type) {
    		this.type = type;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getCode() {
    		return code;
    	}

    	public void setCode(String code) {
    		this.code = code;
    	}

    	public String getContent() {
    		return content;
    	}

    	public void setContent(String content) {
    		this.content = content;
    	}

    	public String getName() {
    		return name;
    	}

    	public void setName(String name) {
    		this.name = name;
    	}

    	public String getScence() {
    		return scence;
    	}

    	public void setScence(String scence) {
    		this.scence = scence;
    	}

}
