package com.ikkong.dg.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-11-14 18:03:41
 */
@Table(name = "dg_items_reject")
@BindID(name = "id")
@SuppressWarnings("serial")
public class ItemsReject extends BaseModel {
    	private Long id;
    	private Long dg_userid;
    	private String mark;
    	private Long work_order_id;
    	private Date create_time;
    	private Integer version;

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Long getDg_userid() {
    		return dg_userid;
    	}

    	public void setDg_userid(Long dg_userid) {
    		this.dg_userid = dg_userid;
    	}

    	public String getMark() {
    		return mark;
    	}

    	public void setMark(String mark) {
    		this.mark = mark;
    	}

    	public Long getWork_order_id() {
    		return work_order_id;
    	}

    	public void setWork_order_id(Long work_order_id) {
    		this.work_order_id = work_order_id;
    	}

    	public Date getCreate_time() {
    		return create_time;
    	}

    	public void setCreate_time(Date create_time) {
    		this.create_time = create_time;
    	}

		public Integer getVersion() {
			return version;
		}

		public void setVersion(Integer version) {
			this.version = version;
		}

}
