package com.ikkong.dg.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
@Table(name = "dg_order_progress")
@BindID(name = "id")
@SuppressWarnings("serial")
public class OrderProgress extends BaseModel {
    	private Long id;
    	private Integer status; //状态，0提交，1确认，2默认    	
    	private Long create_id; //创建电工用户id
    	private String location;//地理位置地址
    	private Double latitude; //纬度坐标
    	private Double longitude; //经度坐标
    	private String mark;
    	private Long work_order_id; //项目子单id
    	private Date create_time; //进度提交时间
    	private Integer version;

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public Long getCreate_id() {
    		return create_id;
    	}

    	public void setCreate_id(Long create_id) {
    		this.create_id = create_id;
    	}

    	public Double getLatitude() {
    		return latitude;
    	}

    	public void setLatitude(Double latitude) {
    		this.latitude = latitude;
    	}

    	public Double getLongitude() {
    		return longitude;
    	}

    	public void setLongitude(Double longitude) {
    		this.longitude = longitude;
    	}

    	public String getMark() {
    		return mark;
    	}

    	public void setMark(String mark) {
    		this.mark = mark;
    	}

    	public Long getWork_order_id() {
    		return work_order_id;
    	}

    	public void setWork_order_id(Long work_order_id) {
    		this.work_order_id = work_order_id;
    	}

    	public Date getCreate_time() {
    		return create_time;
    	}

    	public void setCreate_time(Date create_time) {
    		this.create_time = create_time;
    	}

		public String getLocation() {
			return location;
		}

		public void setLocation(String location) {
			this.location = location;
		}

}
