package com.ikkong.dg.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-10-28 20:22:10
 */
@Table(name = "dg_user_head_ico")
@BindID(name = "ico_id")
@SuppressWarnings("serial")
public class UserHeadIco extends BaseModel {
    	private Long ico_id; //头像ID
    	private Integer status; //图片状态(0:启用,1:待审核)
    	private Integer version;
    	private String pic_name; //图片名
    	private String pic_path; //图片地址
    	private Long user_id; //电工用户Id
    	private Date create_tm; //创建时间

    	@AutoID
    	public Long getIco_id() {
    		return ico_id;
    	}

    	public void setIco_id(Long ico_id) {
    		this.ico_id = ico_id;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getPic_name() {
    		return pic_name;
    	}

    	public void setPic_name(String pic_name) {
    		this.pic_name = pic_name;
    	}

    	public String getPic_path() {
    		return pic_path;
    	}

    	public void setPic_path(String pic_path) {
    		this.pic_path = pic_path;
    	}

    	public Date getCreate_tm() {
    		return create_tm;
    	}

    	public Long getUser_id() {
			return user_id;
		}

		public void setUser_id(Long user_id) {
			this.user_id = user_id;
		}

		public void setCreate_tm(Date create_tm) {
    		this.create_tm = create_tm;
    	}

}
