package com.ikkong.dg.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-10-23 20:44:08
 */
@Table(name = "dg_worktype_check")
@BindID(name = "id")
@SuppressWarnings("serial")
public class WorktypeCheck extends BaseModel {
    	private Long id;
    	
    	private Integer work_id; //工种类型id
    	private Integer admin_id; //审核管理员id
    	private Long dg_user_id; //电工用户id
    	private Long user_worktype_id;//用户工种Id
    	private String id_code;//身份证号
    	private String idcard_down; //身份证反面
    	private String idcard_up; //身份证正面
    	private String mark; //审核失败说明
    	private String qualif_cert; //资格证书
    	private Integer status; //审核状态0待审核，1审核通过，2审核失败
    	private Date create_tm; //创建时间
    	private Date update_tm; //修改时间
    	private Integer version; //版本记录号

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public Integer getWork_id() {
    		return work_id;
    	}

    	public void setWork_id(Integer work_id) {
    		this.work_id = work_id;
    	}

    	public Long getDg_user_id() {
    		return dg_user_id;
    	}

    	public void setDg_user_id(Long dg_user_id) {
    		this.dg_user_id = dg_user_id;
    	}

    	public String getIdcard_down() {
    		return idcard_down;
    	}

    	public void setIdcard_down(String idcard_down) {
    		this.idcard_down = idcard_down;
    	}

    	public String getIdcard_up() {
    		return idcard_up;
    	}

    	public void setIdcard_up(String idcard_up) {
    		this.idcard_up = idcard_up;
    	}

    	public String getMark() {
    		return mark;
    	}

    	public void setMark(String mark) {
    		this.mark = mark;
    	}

    	public String getQualif_cert() {
    		return qualif_cert;
    	}

    	public void setQualif_cert(String qualif_cert) {
    		this.qualif_cert = qualif_cert;
    	}

    	public Integer getStatus() {
			return status;
		}

		public void setStatus(Integer status) {
			this.status = status;
		}

		public Date getCreate_tm() {
    		return create_tm;
    	}

    	public void setCreate_tm(Date create_tm) {
    		this.create_tm = create_tm;
    	}

		public String getId_code() {
			return id_code;
		}

		public void setId_code(String id_code) {
			this.id_code = id_code;
		}

		public Integer getAdmin_id() {
			return admin_id;
		}

		public void setAdmin_id(Integer admin_id) {
			this.admin_id = admin_id;
		}

		public Long getUser_worktype_id() {
			return user_worktype_id;
		}

		public void setUser_worktype_id(Long user_worktype_id) {
			this.user_worktype_id = user_worktype_id;
		}

		public Date getUpdate_tm() {
			return update_tm;
		}

		public void setUpdate_tm(Date update_tm) {
			this.update_tm = update_tm;
		}
}
