package com.ikkong.dg.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.dg.model.AuditFiles;
import com.ikkong.dg.service.AuditFilesService;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
public class AuditFilesServiceImpl extends BaseService<AuditFiles> implements AuditFilesService{

}
