package com.ikkong.dg.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.dg.model.Business;
import com.ikkong.dg.service.BusinessService;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
public class BusinessServiceImpl extends BaseService<Business> implements BusinessService{

}
