package com.ikkong.dg.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.dg.model.DgOrder;
import com.ikkong.dg.service.DgOrderService;

/**
 * Generated by Blade.
 * 2017-10-01 21:21:43
 */
public class DgOrderServiceImpl extends BaseService<DgOrder> implements DgOrderService{

}
