package com.ikkong.dg.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.dg.model.ItemsReject;
import com.ikkong.dg.service.ItemsRejectService;

/**
 * Generated by Blade.
 * 2017-11-14 18:03:41
 */
public class ItemsRejectServiceImpl extends BaseService<ItemsReject> implements ItemsRejectService{

}
