package com.ikkong.dg.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.dg.model.Messages;
import com.ikkong.dg.service.MessagesService;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
public class MessagesServiceImpl extends BaseService<Messages> implements MessagesService{

}
