package com.ikkong.dg.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.dg.model.OrderApply;
import com.ikkong.dg.service.OrderApplyService;

/**
 * Generated by Blade.
 * 2017-10-02 11:50:45
 */
public class OrderApplyServiceImpl extends BaseService<OrderApply> implements OrderApplyService{

}
