package com.ikkong.dg.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.dg.model.OrderProgress;
import com.ikkong.dg.service.OrderProgressService;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
public class OrderProgressServiceImpl extends BaseService<OrderProgress> implements OrderProgressService{

}
