package com.ikkong.dg.service.impl;

import java.util.Date;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.core.constant.CommConts;
import com.ikkong.core.constant.ConstCache;
import com.ikkong.core.shiro.DgUserToken;
import com.ikkong.dg.model.UserHeadIco;
import com.ikkong.dg.service.UserHeadIcoService;
import com.jfinal.plugin.ehcache.CacheKit;

/**
 * Generated by Blade. 2017-10-28 20:22:10
 */
public class UserHeadIcoServiceImpl extends BaseService<UserHeadIco> implements UserHeadIcoService {

	@Override
	public void saveHeadIco(String imageName, String imagePath, Long userId) {
		UserHeadIco ico = new UserHeadIco();
		ico.setCreate_tm(new Date());
		ico.setPic_name(imageName);
		ico.setPic_path(imagePath);
		ico.setStatus(0);// 图片状态(0:启用,1:待审核)
		ico.setVersion(1);
		ico.setUser_id(userId);
		save(ico);
	}

}
