package com.ikkong.dg.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.dg.model.UserWorktype;
import com.ikkong.dg.service.UserWorktypeService;

/**
 * Generated by Blade.
 * 2017-10-28 23:51:23
 */
public class UserWorktypeServiceImpl extends BaseService<UserWorktype> implements UserWorktypeService{

}
