package com.ikkong.dg.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.dg.model.WorkType;
import com.ikkong.dg.service.WorkTypeService;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
public class WorkTypeServiceImpl extends BaseService<WorkType> implements WorkTypeService{

}
