package com.ikkong.dg.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.dg.model.WorktypeCheck;
import com.ikkong.dg.service.WorktypeCheckService;

/**
 * Generated by Blade.
 * 2017-10-20 09:25:28
 */
public class WorktypeCheckServiceImpl extends BaseService<WorktypeCheck> implements WorktypeCheckService{

}
