package com.ikkong.dg.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.dg.model.DgUser;
import com.ikkong.dg.model.vo.DgUserInfo;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
public interface DgUserService extends IService<DgUser>{

	DgUserInfo findByUserId(Long id);
}
