package com.ikkong.dg.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.dg.model.UserWorktype;

/**
 * Generated by Blade.
 * 2017-10-28 23:51:23
 */
public interface UserWorktypeService extends IService<UserWorktype>{

}
