package com.ikkong.dg.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.dg.model.WorkOrder;
import com.ikkong.dg.service.WorkOrderService;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
public class WorkOrderServiceImpl extends BaseService<WorkOrder> implements WorkOrderService{

}
