package com.ikkong.dg.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.dg.model.WorkType;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
public interface WorkTypeService extends IService<WorkType>{

}
