package com.ikkong.dg.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.dg.model.DgMsgTemplate;

/**
 * Generated by Blade.
 * 2017-11-30 17:38:21
 */
public interface DgMsgTemplateService extends IService<DgMsgTemplate>{

}
