package com.ikkong.dg.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.dg.model.ItemsReject;

/**
 * Generated by Blade.
 * 2017-11-14 18:03:41
 */
public interface ItemsRejectService extends IService<ItemsReject>{

}
