package com.ikkong.dg.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.dg.model.OrderApply;

/**
 * Generated by Blade.
 * 2017-10-02 11:50:45
 */
public interface OrderApplyService extends IService<OrderApply>{

}
