package com.ikkong.dg.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.dg.model.WorktypeCheck;

/**
 * Generated by Blade.
 * 2017-10-20 09:25:28
 */
public interface WorktypeCheckService extends IService<WorktypeCheck>{

}
