package com.ikkong.dg.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.dg.model.WorkOrder;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
public interface WorkOrderService extends IService<WorkOrder>{

}
