package com.ikkong.dg.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.dg.model.DgMsgTemplate;
import com.ikkong.dg.service.DgMsgTemplateService;

/**
 * Generated by Blade.
 * 2017-11-30 17:38:21
 */
public class DgMsgTemplateServiceImpl extends BaseService<DgMsgTemplate> implements DgMsgTemplateService{

}
