package com.ikkong.dg.controller;

import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.dg.model.AuditFiles;
import com.ikkong.dg.service.AuditFilesService;
import com.ikkong.dg.service.impl.AuditFilesServiceImpl;
import com.ikkong.system.controller.base.UrlPermissController;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
public class AuditFilesController extends UrlPermissController {
	private static String CODE = "auditFiles";
	private static String PERFIX = "dg_audit_files";
	private static String LIST_SOURCE = "AuditFiles.list";
	private static String BASE_PATH = "/dg/auditFiles/";
	
	AuditFilesService service = new AuditFilesServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "auditFiles.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "auditFiles_add.html");
	}

	public void edit() {
		String id = getPara(0);
		AuditFiles auditFiles = service.findById(id);
		setAttr("model", JsonKit.toJson(auditFiles));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "auditFiles_edit.html");
	}

	public void view() {
		String id = getPara(0);
		AuditFiles auditFiles = service.findById(id);
		setAttr("model", JsonKit.toJson(auditFiles));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "auditFiles_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		AuditFiles auditFiles = mapping(PERFIX, AuditFiles.class);
		boolean temp = service.save(auditFiles);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		AuditFiles auditFiles = mapping(PERFIX, AuditFiles.class);
		auditFiles.setVersion(auditFiles.getVersion()+1);
		boolean temp = service.update(auditFiles);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
