package com.ikkong.dg.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-10-28 23:51:23
 */
@Table(name = "dg_user_worktype")
@BindID(name = "id")
@SuppressWarnings("serial")
public class UserWorktype extends BaseModel {
    	private Long id; //唯一ID
    	private Integer status; //审核状态
    	private Long dg_userid; //电工ID
    	private Long worktype_id; //工种ID
    	private Date create_time; //创建时间
    	private Integer version; //版本号

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public Date getCreate_time() {
    		return create_time;
    	}

    	public void setCreate_time(Date create_time) {
    		this.create_time = create_time;
    	}

		public Long getDg_userid() {
			return dg_userid;
		}

		public void setDg_userid(Long dg_userid) {
			this.dg_userid = dg_userid;
		}

		public Long getWorktype_id() {
			return worktype_id;
		}

		public void setWorktype_id(Long worktype_id) {
			this.worktype_id = worktype_id;
		}

}
