package com.ikkong.dg.controller;

import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.dg.model.OrderProgress;
import com.ikkong.dg.service.OrderProgressService;
import com.ikkong.dg.service.impl.OrderProgressServiceImpl;
import com.ikkong.system.controller.base.UrlPermissController;

/**
 * Generated by Blade.
 * 2017-09-24 12:44:38
 */
public class OrderProgressController extends UrlPermissController {
	private static String CODE = "orderProgress";
	private static String PERFIX = "dg_orde_progress";
	private static String LIST_SOURCE = "orderProgress.list";
	private static String BASE_PATH = "/dg/orderProgress/";
	
	OrderProgressService service = new OrderProgressServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "orderProgress.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "orderProgress_add.html");
	}

	public void edit() {
		String id = getPara(0);
		OrderProgress orderProgress = service.findById(id);
		setAttr("model", JsonKit.toJson(orderProgress));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "orderProgress_edit.html");
	}

	public void view() {
		String id = getPara(0);
		OrderProgress orderProgress = service.findById(id);
		setAttr("model", JsonKit.toJson(orderProgress));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "orderProgress_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		OrderProgress orderProgress = mapping(PERFIX, OrderProgress.class);
		boolean temp = service.save(orderProgress);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		OrderProgress orderProgress = mapping(PERFIX, OrderProgress.class);
		orderProgress.setVersion(orderProgress.getVersion()+1);
		boolean temp = service.update(orderProgress);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
