package com.ikkong.dg.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.dg.model.DgOrder;

/**
 * Generated by Blade.
 * 2017-10-01 21:21:43
 */
public interface DgOrderService extends IService<DgOrder>{

}
