package com.ikkong.dg.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-10-02 11:50:45
 */
@Table(name = "dg_order_apply")
@BindID(name = "id")
@SuppressWarnings("serial")
public class OrderApply extends BaseModel {
    	private Long id;
    	private Integer status; //状态，0申请中，1同意，2拒绝，3挂起
    	private Integer type; //申请类型，0空，1招标申请，2订单终止申请，3订单加班申请
    	private Integer version;
    	private Long create_id; //创建电工用户id
    	private String mark; //招标说明，100汉字以内
    	private Long work_order_id; //订单id
    	private Date create_time; //创建时间
    	private String audit_desc;//审核描述

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getType() {
    		return type;
    	}

    	public void setType(Integer type) {
    		this.type = type;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public Long getCreate_id() {
    		return create_id;
    	}

    	public void setCreate_id(Long create_id) {
    		this.create_id = create_id;
    	}

    	public String getMark() {
    		return mark;
    	}

    	public void setMark(String mark) {
    		this.mark = mark;
    	}

    	public Date getCreate_time() {
    		return create_time;
    	}

    	public void setCreate_time(Date create_time) {
    		this.create_time = create_time;
    	}

		public Long getWork_order_id() {
			return work_order_id;
		}

		public void setWork_order_id(Long work_order_id) {
			this.work_order_id = work_order_id;
		}

		public String getAudit_desc() {
			return audit_desc;
		}

		public void setAudit_desc(String audit_desc) {
			this.audit_desc = audit_desc;
		}

}
